### ISSUE TITLE
Adding logging Module

### ISSUE THREAD

**Issue by umangtank** [nikki-priyaHIT/Project-Exp-Recog#24]
Hello

I am a GSSoC22 contributor. I would like to add logging module to save all the logs.
Can you please assign this....Thank You 👍🏻

**Comment by nikki-priyaHIT** [comment]
@umangtank what's the progress, please update

**Comment by umangtank** [comment]
@nikki-priyaHIT   I make a PR and you approved it and merged with master branch..

**Comment by nikki-priyaHIT** [comment]
@umangtank are you still working on this issue?

**Comment by umangtank** [comment]
No, I already  done my task.
