### ISSUE TITLE
Detect via webcam

### ISSUE THREAD

**Issue by nikki-priyaHIT** [nikki-priyaHIT/Project-Exp-Recog#6]

**Comment by aritra1804** [comment]
I would like to work on this issue FOR gssoc 22

**Comment by nikki-priyaHIT** [comment]
> I would like to work on this issue FOR gssoc 22

hey @aritra1804 since @abh139 is working on this issue u can create new issue for this project

**Comment by Roshaen** [comment]
Hello @nikki-priyaHIT 
Greetings!!
I would like to work on this issue for GSSOC'22
Please assign me.

**Comment by abh139** [comment]
@nikki-priyaHIT I am unable to set the environment its throwing error again nd again. Pls assign to someone else

**Comment by Roshaen** [comment]
@nikki-priyaHIT I can work on this

**Comment by aritra1804** [comment]
Even I can work on it

**Comment by amgad-div** [comment]
I would like to work on this issue FOR gssoc 22

**Comment by Parth-Shete** [comment]
I have experience of working on this issue/technology, I am also a GSSOC 22 contributor, if no one is doing the project, please assign me this issue.

**Comment by yashh18** [comment]
Hello i am a GSSC'22 contributor
Please assign me this issue if the person fails to complete within time!

**Comment by nikki-priyaHIT** [comment]
@Roshaen What's the progress?

**Comment by nikki-priyaHIT** [comment]
@Roshaen What's the Update?

**Comment by Roshaen** [comment]
Hey, @nikki-priyaHIT due to my exams I'm currently not able to work on this issue. I apologize for the inconvenience.

**Comment by aritra1804** [comment]
Hey can I work on this issue,if @Roshaen is busy

**Comment by nikki-priyaHIT** [comment]
@aritra1804 Yes, You can...

**Comment by aritra1804** [comment]
Hey @nikki-priyaHIT could you explain in detail what should i do

**Comment by Purva-Gharat** [comment]
Can I work on this issue? I have previously worked on this problem statement so it will take less time for me to make a PR for it please assign this to me.

**Comment by nikki-priyaHIT** [comment]
@aritra1804 make changes so that we could detect via webcam also not only from provided video or images

**Comment by Purva-Gharat** [comment]
> @aritra1804 make changes so that we could detect via webcam also not only from provided video or images

If he is not working on it can you please assign this issue to me coz I have worked on this and my code is ready

**Comment by aritra1804** [comment]
> @aritra1804 make changes so that we could detect via webcam also not only from provided video or images

Ok will do

**Comment by aritra1804** [comment]
hey @nikki-priyaHIT kindly close this issue since pr has been merged
